### ISSUE TITLE
급여 int형으로

### ISSUE THREAD

**Issue by dohvis** [ChungPa/GoJob#21]
그래야 정렬가능
- 월급 --> 시급, 시급 --> 월급 필요할까?

**Comment by Kcrong** [comment]
월급인지 시급인지 체크하는게 어려울듯
따로 생각해둔 방법 있어?

**Comment by dohvis** [comment]
시급이랑 월급이란 텍스트를 동시에 넣어두는 경우가 없었던거같은데 
1. if '시급' in pay 이런식으로하고 
2. 노동시간있나 찾아보고 없으면 주5일 하루 7시간정도로 디폴트 잡고
3. 정규식으로 짜르고 시급이면 *7 \* (전체 일 - 주말 수)

**Comment by Kcrong** [comment]
'시급' 이라는 텍스트가 없는 경우도 있었어 
아 월급은 '만원' 이라고 쓰고 시급은 '원' 이렇게 쓰는것 같던데 이렇게 해볼까?
2,3 번은 괜찮은 듯

**Comment by dohvis** [comment]
시급이 만원넘으면 포함될수도 있을꺼같은디.. 이따가 한번 더봐야겠다

**Comment by Kcrong** [comment]
첫 단어가 
'시급' -> 금액 \* 7(시간) \* 5(일) \* 4(주)
'월급' -> 그대로
'연봉' -> 금액 / 12(개월)
